version: "3"

services:
  laravel:    
    build: .
    working_dir: /var/www
    container_name: laravue
    ports:
      - 8080:8080
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./docker/apache2/httpd-vhosts.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./:/var/www
    depends_on:
      - mysql
      - redis

  redis:
    image: redis:alpine

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=laravue
      - MYSQL_USER=carlo
      - MYSQL_PASSWORD=P@ssw0rd
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql:/var/lib/mysql

